# checks/vm/dhcp-addressing.nix — OWN-1, TEST-2.
#
# The incident this repo is being rebuilt around: a default-deny input chain on
# a DHCP-addressed host, written in a repo that could not see how the host got
# its address. The rule that was missing is now DERIVED from
# `nixnet.interfaces.<if>.addressing.v4`, and this test is what makes the
# derivation load-bearing rather than decorative.
#
# ── WHAT IS ACTUALLY OBSERVABLE, MEASURED ──────────────────────────────────
# Two things were measured in a VM before this test was written, because the
# obvious test is vacuous and the second-most-obvious one is too:
#
#   1. "Does it still have an address after boot" proves NOTHING. The initial
#      DISCOVER/REQUEST goes out over AF_PACKET and never traverses netfilter,
#      so a host with no DHCP rule at all comes up addressed and healthy.
#
#   2. "Wait out a lease and check the address" ALSO proves nothing, for two
#      independent reasons, both measured:
#        a. The unicast RENEW leg is rescued by the preamble's
#           `ct state established,related accept`: the request goes out over a
#           UDP socket, conntrack records it, and the reply matches the reply
#           tuple. Measured with a counter as the last rule before the policy
#           drop: 0 packets over 9 renewals with no DHCP rule present.
#        b. Even when the renew leg is forced off the UDP path entirely, both
#           dhcpcd and systemd-networkd fall back to a raw AF_PACKET socket for
#           BOTH send and receive -- and AF_PACKET delivery happens before the
#           netfilter input hook. Measured: 13 of 13 DHCP replies hit the
#           policy drop while the client renewed its lease anyway and kept its
#           address for the full run.
#
# So the consequence "the host loses its address" is NOT reproducible against
# these clients, and a test asserting it would fail forever for the wrong
# reason. What IS observable, exactly and deterministically, is the packet
# verdict: whether the host's own filter admits or drops real DHCP replies
# generated by a real renewal, and whether that verdict follows the declared
# addressing fact. That is what this test asserts, at the point where the
# derivation either happened or did not.
#
# The `vmtest` scaffold table below is TEST SCAFFOLDING, not a thing under
# test. Its output rule drops the client's unicast renew so the exchange falls
# onto the broadcast leg, which conntrack cannot rescue (see 2a) -- without it
# the derived rule is never consulted and the check passes against a ruleset
# that does not contain it. Its two observer chains straddle nixnet's input
# chain: `raw` priority runs before it and counts arrivals, `filter + 10` runs
# after it and therefore counts only what nixnet ACCEPTED, since a base chain's
# drop is final across the hook.

{ pkgs }:

let
  # A real DHCPv4 client on eth1. The test-driver network module hands every
  # node a static address on its vlan; that is cleared here, because a static
  # address renews nothing and the renewal path is the entire subject.
  dhcpClient = { lib, ... }: {
    virtualisation.vlans = [ 1 ];
    networking.useDHCP = false;
    networking.interfaces.eth1 = {
      ipv4.addresses = lib.mkForce [ ];
      useDHCP = true;
    };
  };

  # Scaffolding: see this file's header. One table, three chains, none of them
  # nixnet's. Applied from the test script rather than from NixOS config, so it
  # arrives the way a foreign table really does -- after nixnet's own apply.
  scaffold = {
    environment.etc."vmtest-scaffold.nft".text = ''
      table inet vmtest
      delete table inet vmtest

      table inet vmtest {
        # Before nixnet's chain: everything that arrived.
        chain observe_pre {
          type filter hook input priority raw; policy accept;
          meta nfproto ipv4 udp sport 67 udp dport 68 counter
        }

        # After nixnet's chain: only what nixnet accepted, because a base
        # chain's drop verdict is final across every chain at the hook.
        chain observe_post {
          type filter hook input priority filter + 10; policy accept;
          meta nfproto ipv4 udp sport 67 udp dport 68 counter
        }

        # Force the exchange off the unicast renew leg, which conntrack
        # rescues regardless of any DHCP rule, and onto the broadcast leg,
        # which it cannot.
        chain force_rebind {
          type filter hook output priority filter; policy accept;
          udp dport 67 ip daddr != 255.255.255.255 counter drop
        }
      }
    '';
  };
in
{
  name = "dhcp-addressing";
  behaviours = [ "OWN-1" "TEST-2" ];
  requiresModules = [ "firewall.nix" ];
  requiresOptions = [
    [ "nixnet" "firewall" "enable" ]
    [ "nixnet" "firewall" "management" "interfaces" ]
    [ "nixnet" "interfaces" "addressing" "v4" ]
  ];

  test = { modules, baseline }: {
    name = "nixnet-dhcp-addressing";

    nodes = {
      # The DHCP server. Deliberately short lease: renew at 6s, rebind at 12s,
      # expiry at 30s, so the test drives several complete lease cycles inside
      # a minute rather than asserting at the one moment the bug is invisible.
      router = { ... }: {
        imports = [ baseline ];
        virtualisation.vlans = [ 1 ];
        services.kea.dhcp4 = {
          enable = true;
          settings = {
            interfaces-config.interfaces = [ "eth1" ];
            lease-database = { type = "memfile"; persist = false; };
            valid-lifetime = 30;
            renew-timer = 6;
            rebind-timer = 12;
            subnet4 = [{
              id = 1;
              subnet = "192.168.1.0/24";
              pools = [{ pool = "192.168.1.100 - 192.168.1.150"; }];
            }];
          };
        };
      };

      # Declares the truth: this interface is DHCP-addressed on v4.
      declared = { ... }: {
        imports = [ modules.core modules.firewall baseline dhcpClient scaffold ];
        nixnet.interfaces.eth1.addressing = { v4 = "dhcp"; v6 = "none"; };
        nixnet.firewall = {
          enable = true;
          management.interfaces = [ "eth1" ];
        };
      };

      # The control, and the whole point of having one. Identical firewall,
      # identical DHCP client, one different declared fact: nixnet is told
      # something else owns v4 here, so it must derive nothing for it. If both
      # nodes end up with the same ruleset, the "derivation" is a constant.
      undeclared = { ... }: {
        imports = [ modules.core modules.firewall baseline dhcpClient scaffold ];
        nixnet.interfaces.eth1.addressing = { v4 = "unmanaged"; v6 = "unmanaged"; };
        nixnet.firewall = {
          enable = true;
          management.interfaces = [ "eth1" ];
        };
      };
    };

    testScript = ''
      import re

      start_all()
      router.wait_for_unit("kea-dhcp4-server.service")

      clients = [declared, undeclared]

      def addr(m):
          out = m.succeed("ip -4 -o addr show dev eth1 || true")
          hit = re.search(r"inet (\d+\.\d+\.\d+\.\d+)", out)
          return hit.group(1) if hit else None

      def counter(m, chain):
          out = m.succeed(
              f"nft -j list chain inet vmtest {chain} | "
              "jq '[.nftables[] | select(.rule) | .rule.expr[] | "
              "select(.counter) | .counter.packets] | add // 0'"
          )
          return int(out.strip())

      for m in clients:
          m.wait_for_unit("nixnet-firewall.service")
          m.wait_for_unit("multi-user.target")
          # Scaffolding, applied as its own table -- which nixnet must tolerate
          # (FW-2 has its own test; here a surviving scaffold is a precondition
          # for measuring anything at all).
          m.succeed("nft -f /etc/vmtest-scaffold.nft")
          m.wait_until_succeeds("ip -4 -o addr show dev eth1 | grep -q 'inet '", timeout=120)

      initial = {m.name: addr(m) for m in clients}
      for name, a in initial.items():
          assert a is not None, f"{name} never got a DHCPv4 address at all"

      # ── the derivation, read off the LIVE kernel ruleset ────────────────
      # Not the rendered text: what the kernel is enforcing.
      declared.succeed("nft list table inet nixnet | grep -q 'udp sport 67'")
      undeclared.fail("nft list table inet nixnet | grep -q 'udp sport 67'")

      # Three full lease lifetimes, with the unicast renew leg dropped on
      # egress by the scaffold so every exchange takes the broadcast path.
      declared.succeed("sleep 80")

      # ── the verdict on real renewal traffic ────────────────────────────
      arrived_d, survived_d = counter(declared, "observe_pre"), counter(declared, "observe_post")
      arrived_u, survived_u = counter(undeclared, "observe_pre"), counter(undeclared, "observe_post")

      assert arrived_d > 0, "no DHCP replies reached the declared node's filter at all -- the test measured nothing"
      assert arrived_u > 0, "no DHCP replies reached the control node's filter at all -- the test measured nothing"
      assert survived_d == arrived_d, (
          "declared node dropped DHCP replies its own addressing declaration should have admitted: "
          f"{arrived_d} arrived, {survived_d} passed the filter"
      )
      assert survived_u == 0, (
          "the control node -- which declares nothing about v4 addressing -- admitted "
          f"{survived_u} of {arrived_u} DHCP replies. Something other than the derived rule "
          "is letting them through, so this suite is not measuring the derivation."
      )

      # ── TEST-2, literally: held past lease expiry, still addressed, and
      # still reachable FROM THE OTHER MACHINE over the interface concerned.
      assert addr(declared) == initial["declared"], (
          f"declared node's address changed under renewal: {initial['declared']} -> {addr(declared)}"
      )
      router.succeed(f"ping -c 2 -W 5 {initial['declared']}")

      # The control keeps its address too, and that is not a contradiction --
      # it is the measured fact this file's header documents: both dhcpcd and
      # systemd-networkd fall back to AF_PACKET, which is delivered before the
      # input hook, so a dropped reply is still a received reply. Asserted so
      # the day it stops being true is a build failure and not a silent
      # weakening: when this fails, the address itself has become the
      # observable and the packet counters above can be demoted to a detail.
      assert addr(undeclared) is not None, (
          "the control node LOST its address -- address loss is now observable, so this test "
          "should assert on the address directly instead of on packet counters"
      )
    '';
  };
}
